apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wellbing-data-pvc
  namespace: hoyaweb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
